#!/bin/bash
mkdir backend
mkdir frontend
mkdir mariadb
mkdir mariadb/master                  
mkdir mariadb/slave                 
mkdir mariadb/master/volume           
mkdir mariadb/master/sql              
mkdir mariadb/master/config           
mkdir mariadb/slave/volume            
mkdir mariadb/slave/sql                
mkdir mariadb/slave/config             
cd backend
mkdir web
mkdir nginx
cd ..
mkdir backend/web/static
mkdir frontend/nginx
mkdir frontend/web-front
touch backend/web/.env
touch backend/web/Dockerfile
touch backend/web/create_superuser.py    
touch backend/web/requirements.txt
touch backend/nginx/Dockerfile.dev
touch backend/nginx/default.dev.conf
touch frontend/nginx/Dockerfile.dev
touch frontend/nginx/default.dev.conf
touch frontend/nginx/wait.sh